# Generated by Django 3.2 on 2021-04-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(default='', max_length=1000, verbose_name='Content'),
        ),
    ]
