# Generated by Django 3.2 on 2021-04-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publication_date',
            field=models.DateField(auto_now_add=True, verbose_name='Publication Date'),
        ),
    ]
